services:
  cache-server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - fake-gcs
      - postgres
      - redis
    environment:
      API_BASE_URL: http://localhost:3000
      STORAGE_DRIVER: gcs
      STORAGE_GCS_BUCKET: test-bucket
      STORAGE_GCS_ENDPOINT: http://fake-gcs:4443/storage/v1/
      DB_DRIVER: postgres
      DB_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      REDIS_URL: redis://redis:6379
      DEBUG: 'true'

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    entrypoint: [sh]
    command:
      [-c, 'mkdir -p /data/test-bucket && /bin/fake-gcs-server -scheme http -port 4443 -data /data']
    ports:
      - 4443:4443
