apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-actions-cache-server.fullname" . }}
  labels:
    {{- include "github-actions-cache-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "github-actions-cache-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "github-actions-cache-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "github-actions-cache-server.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ include "github-actions-cache-server.fullname" . }}
            - secretRef:
                name: {{ include "github-actions-cache-server.fullname" . }}
          {{- if .Values.redis.enabled }}
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "github-actions-cache-server.fullname" . }}
                  key: REDIS_URL
            - name: REDIS_TTL
              value: {{ .Values.redis.ttl | quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
