apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-actions-cache-server.fullname" . }}
  labels:
    {{- include "github-actions-cache-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
